version: '3.7'

services:
  db:
    container_name: db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    cap_add:
      - SYS_NICE
  client:
    container_name: client
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
  server:
    container_name: server
    build: ./server
    ports:
      - 8080:8080
      - 4242:4242
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}