version: '3.7'

services:
  db:
    container_name: db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database_development
      MYSQL_PASSWORD: root
    cap_add:
      - SYS_NICE
    networks:
      - app-network
  client:
    container_name: client
    build: ./client
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
      - web-root:/build
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-network
  server:
    container_name: server
    build: ./server
    ports:
      - 8080:8080
      - 4242:4242
    volumes:
      - ./server:/app
      - /app/node_modules
      - web-root:/public
    depends_on:
      - db
    environment:
      - NODE_ENV=development
    networks:
      - app-network
  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      #- certbot-etc:/etc/letsencrypt
      #- certbot-var:/var/lib/letsencrypt
    depends_on:
      - server
    networks:
      - app-network
volumes:
  web-root:
networks:
  app-network:
    driver: bridge
