version: '3.7'

services:
  db:
    container_name: db
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root${DB_PASSWORD?err}"
      MYSQL_DATABASE: "${DB_NAME?err}"
      MYSQL_USER: "${DB_USERNAME?err}"
      MYSQL_PASSWORD: "${DB_PASSWORD?err}"
    cap_add:
      - SYS_NICE
  client:
    container_name: client
    build: 
      context: ./client
      args:
        - node_env="${NODE_ENV?err}"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
  server:
    container_name: server
    build: ./server
    ports:
      - 8080:8080
      - 4242:4242
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      - "NODE_ENV=${NODE_ENV?err}"
      - "DB_NAME=${DB_NAME?err}"
      - "DB_USERNAME=${DB_USERNAME?err}"
      - "DB_PASSWORD=${DB_PASSWORD?err}"