export const CREATE_SHOP_REQUEST = 'CREATE_SHOP_REQUEST';
export const CREATE_SHOP_SUCCESS = 'CREATE_SHOP_SUCCESS';
export const CREATE_SHOP_FAILURE = 'CREATE_SHOP_FAILURE';
export const SET_DELIVERY_AREA = 'SET_DELIVERY_AREA';
export const SET_SHOP = 'SET_SHOP';
export const GET_LAT_LNG_REQUEST = 'GET_LAT_LNG_REQUEST';
export const GET_LAT_LNG_SUCCESS = 'GET_LAT_LNG_SUCCESS';
export const GET_LAT_LNG_FAILURE = 'GET_LAT_LNG_FAILURE';