export const ADD_TO_CART = 'ADD_TO_CART';
export const EDIT_QUANTITY = 'EDIT_QUANTITY';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST';
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS';
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE';
export const RESET_CART = 'RESET_CART';