export const REQUEST_QUOTE_REQUEST = 'REQUEST_QUOTE_REQUEST';
export const REQUEST_QUOTE_SUCCESS = 'REQUEST_QUOTE_SUCCESS';
export const REQUEST_QUOTE_FAILURE = 'REQUEST_QUOTE_FAILURE';
export const GET_QUOTES_REQUEST = 'GET_QUOTES_REQUEST';
export const GET_QUOTES_SUCCESS = 'GET_QUOTES_SUCCESS';
export const GET_QUOTES_FAILURE = 'GET_QUOTES_FAILURE';